### ISSUE TITLE
Maciej Kabała does not go out anymore

### ISSUE THREAD

**Issue by narolski** [Adimus11/CityBuilderAR#1]
There is a serious problem with Maciej Kabała depedency in this project. He refuses to go out like we used to.

Please do provide an urgent, magnanimous fix for this critical difficulty.

**Comment by narolski** [comment]
Mentioning @maxxibull as a direct cause of this issue.

**Comment by adimus11** [comment]
Unfortunately, this is the expected result of living in society.  Maciej Kabała after `1-Lockdown-Patch` introduced by Walczak Sp. ZOOlogiczna, during infrastructure transfer, lost his ability to socialize with others.


Sorry, the issue won't fix

**Comment by narolski** [comment]
First `Elastic`, now `TretSoft`... It is a blue week indeed 👎
