### ISSUE TITLE
Replacing Kabala Dependency 

### ISSUE THREAD

**Issue by okkindel** [Adimus11/CityBuilderAR#2]
According to https://github.com/Adimus11/CityBuilderAR/issues/1. 

I suggest replacing the dependency with some newer one, such as Gogola Engine. This will allow us to get rid of useless elements from the program code.

**Comment by narolski** [comment]
This might also fix the issue related to the bloated codebase.

**Comment by JakubGogola** [comment]
I think you could use some other framework like Hajduk Soft - it's lighter, regularly maintained and date of EOL is not that close

**Comment by adimus11** [comment]
Sounds like a good idea, moving the game out of the AR world into a MultiPlayer Board Inspired game run on a single device. Also, Gogola Graphics Euphoria Engine could be utilized here for improving particle efects.

**Comment by narolski** [comment]
@Adimus11 have you considered `Mucha S(c)haders`? They take quite a lot of time to catch up, but once they do, they make everyone smile!

**Comment by okkindel** [comment]
@narolski `Mucha S(c)haders` starts with the extremely high license costs and the dynamically changing subscription price. It is not a suitable solution for a small, non-commercial project.

**Comment by narolski** [comment]
@Adimus11 what is the state of work on this?

**Comment by JakubGogola** [comment]
@Adimus11 due that issue I can't use your application in my work and I'm losing clients. Could you do something with it ASAP? 🙏

**Comment by adimus11** [comment]
@JakubGogola @narolski  I'm dead inside soo the project will be probably discontinued 🙂

**Comment by JakubGogola** [comment]
I'm sorry to hear that. It's piece of fantastic and quality code!

**Comment by narolski** [comment]
@okkindel please close this issue, since it's dead on the inside much like @JakubGogola claims to be during work hours.

**Comment by okkindel** [comment]
I'm closing because of Jakub's strange sexual preferences.
